name: Bump version
on:
  push:
    branches:
      - master      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 2
      - id: next_version
        uses: zwaldowski/semver-release-action@v1
        with:
         dry_run: true
         bump: major
         github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - run: echo "${{ steps.next_version.outputs.version }}"
      - run: |
         git config --global user.email "raj.vasupilli@gmail.com"
         git config --global user.name "Raju V"
         git add .
         git commit -m "Bump version"
         git push
      - uses: zwaldowski/semver-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ steps.git_commit.outputs.sha }}
