name: Bump version
on:
  push:
    branches:
      - master      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - id: next_version
        uses: zwaldowski/semver-release-action@v1
        with:
         dry_run: true
         bump: major
         github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "${{ steps.next_version.outputs.version }}"
      - run: |
         git add .
         git commit -m "Bump version"
         git push
         echo ::set-output name=sha::$(git rev-parse HEAD)
      - uses: zwaldowski/semver-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ steps.git_commit.outputs.sha }}
